#!/bin/bash
# Runs INSIDE an arm64 container (qemu-user) whose filesystem is the BlackArch
# rootfs under test, as root, with the repository's garden-blackarch/rootfs
# mounted read-only at /builder and a generated keyring script at
# /w/keyring-script.sh. Started by validate-rootfs.sh; never on a phone.
#
# Package-management checks only: nothing from BlackArch is executed or pointed
# at any target. The probe packages are libraries and a perl module.
#
# qemu-user has no seccomp support, so pacman's downloader needs --disable-sandbox
# here (the shipped pacman.conf is not changed by it): an emulation limit,
# reported as such, not a property of the image.
set -u
export LANG=C.UTF-8
PASS=0; FAIL=0
ok() { echo "PASS $*"; PASS=$((PASS + 1)); }
no() { echo "FAIL $*"; FAIL=$((FAIL + 1)); }
tailout() { sed 's/^/    | /' "$1" | tail -${2:-6}; }
check() { local d=$1; shift; if "$@" > /tmp/c.out 2>&1; then ok "$d"; else no "$d"; tailout /tmp/c.out; fi; }
# refuse DESC REGEX CMD...: the command must fail, and say why.
refuse() {
    local d=$1 re=$2; shift 2
    if "$@" > /tmp/c.out 2>&1; then no "$d: ACCEPTED"; tailout /tmp/c.out
    elif grep -Eqi "$re" /tmp/c.out; then ok "$d: refused ($(grep -Eio "$re" /tmp/c.out | head -1))"
    else no "$d: failed for another reason"; tailout /tmp/c.out 8; fi
}
sd="--disable-sandbox"
PK=(perl-color-output libtirpc-compat mbelib)

echo "== D. the image as shipped"
sha256sum /etc/pacman.conf | cut -d' ' -f1 > /tmp/conf.sha
check "no pacman keyring ships" test ! -e /etc/pacman.d/gnupg
check "no sync databases, cache or lock" bash -c 'test -z "$(ls -A /var/lib/pacman/sync)" && test -z "$(ls -A /var/cache/pacman/pkg)" && test ! -e /var/lib/pacman/db.lck'
check "final pacman.conf passes the policy" sh /builder/check-pacman-conf.sh /etc/pacman.conf /builder/keyring.pins
check "repositories: core extra alarm aur blackarch" test "$(pacman-conf --repo-list | tr '\n' ' ')" = "core extra alarm aur blackarch "
check "Architecture = aarch64" test "$(pacman-conf Architecture)" = aarch64
check "blackarch Server is the official aarch64 origin" test "$(pacman-conf --repo blackarch Server)" = "https://blackarch.org/blackarch/blackarch/os/aarch64"
check "global SigLevel requires signatures" bash -c 'pacman-conf SigLevel | tr " " "\n" | grep -Eqx "Required|PackageRequired" && ! pacman-conf SigLevel | tr " " "\n" | grep -Eqx "Never|Optional|TrustAll|PackageNever|PackageOptional|PackageTrustAll"'
check "blackarch overrides no SigLevel (it inherits the global one)" test -z "$(pacman-conf --repo blackarch SigLevel)"
check "keyring data for both distributions ships" bash -c 'for f in archlinuxarm.gpg archlinuxarm-trusted blackarch.gpg blackarch-trusted blackarch-revoked; do test -s /usr/share/pacman/keyrings/$f || exit 1; done'
check "both signature-check packages and signatures ship" bash -c 'cd /usr/share/thothterm/signature-check && ls *.sig | wc -l | grep -qx 2 && ls archlinuxarm-keyring-*.pkg.tar.* blackarch-keyring-*.pkg.tar.zst >/dev/null'
check "edition provenance marker ships" bash -c 'test -s /usr/share/thothterm/blackarch/README && test "$(sha256sum < /usr/share/thothterm/blackarch/keyring.pins)" = "$(sha256sum < /builder/keyring.pins)" && test "$(sha256sum < /usr/share/thothterm/blackarch/blackarch-repo.conf)" = "$(sha256sum < /builder/blackarch-repo.conf)"'
echo "INFO installed packages: $(pacman -Q | wc -l)"
check "pacman -Dk: no database errors" bash -c 'pacman -Dk 2>/dev/null | grep -q "No database errors have been found"'
check "pacman -Qk: no package has missing files" bash -c 'pacman -Qk 2>/dev/null | tee /tmp/qk.out | grep -vc " 0 missing files" | grep -qx 0 && test "$(wc -l < /tmp/qk.out)" -ge 100'
check "no BlackArch tool is preinstalled" bash -c '! pacman -Qq | grep -qx -e blackarch-officials -e "blackarch-.*" -v >/dev/null; test "$(pacman -Qq | grep -c "^blackarch")" = 1'

echo "== H. both keyrings, through the Garden keyring script (generated by RootfsManager for this edition)"
check "the keyring script ends keyring-verified" bash -c 'bash /w/keyring-script.sh 2>&1 | tee /tmp/ks.out | tail -1 | grep -qx keyring-verified'
tailout /tmp/ks.out 3
G="gpg --homedir /etc/pacman.d/gnupg --no-permission-warning --batch"
for k in 68B3537F39A313B3E574D06777193F152BDBE6A6 F9A6E68A711354D84A9B91637533BAFE69A25079 8F9A9793CB8591147C2EC70566E0CDBD1E01F333 A0917C4147A37007CB54C1CFD295AA940EFDDF62 4345771566D76038C7FEB43863EC0ADBEA87E4E3; do
    check "key $k is fully valid in the installation keyring" bash -c "$G --with-colons --list-keys $k | grep -q '^pub:[fu]:'"
done
for k in CBA3C7D4798912702DCF568E67D8BDF42AD93F4E F6DA3545F655964DD9177918C65009B64EB7BB3C 5E210889BBB5C48500E0C4F9C75E985FF8B993B4; do
    echo "INFO key $k validity field: $($G --with-colons --list-keys $k 2>/dev/null | awk -F: '/^pub:/{print $2}')"
done
check "the revoked key is not valid" bash -c "! $G --with-colons --list-keys 5E210889BBB5C48500E0C4F9C75E985FF8B993B4 | grep -q '^pub:[fu]:'"
check "pacman.conf is unchanged by the keyring setup" bash -c 'test "$(sha256sum /etc/pacman.conf | cut -d" " -f1)" = "$(cat /tmp/conf.sha)"'

echo "== F. the real repositories synchronise"
check "pacman -Sy" pacman -Sy $sd
for r in core extra alarm aur blackarch; do check "database $r synchronised" test -s /var/lib/pacman/sync/$r.db; done
n=$(pacman -Sl blackarch | wc -l); echo "INFO blackarch packages: $n"
check "the BlackArch aarch64 catalog is present" test "$n" -ge 4000
sed '/^\[blackarch\]/,$d' /etc/pacman.conf > /tmp/noba.conf
check "without the BlackArch repository exactly one package is foreign: blackarch-keyring" test "$(pacman --config /tmp/noba.conf -Qm 2>/dev/null | cut -d' ' -f1)" = blackarch-keyring
check "with the BlackArch repository nothing is foreign (the keyring is in that repository)" test -z "$(pacman -Qm 2>/dev/null)"
check "pacman kept blackarch.db.sig" test -s /var/lib/pacman/sync/blackarch.db.sig
check "blackarch.db.sig verifies with the installation keyring (signed by the pinned key)" bash -c "$G --status-fd 1 --verify /var/lib/pacman/sync/blackarch.db.sig /var/lib/pacman/sync/blackarch.db 2>/dev/null | grep -q '^\[GNUPG:\] VALIDSIG F9A6E68A711354D84A9B91637533BAFE69A25079 '"

echo "== G+. signed packages install, are validated by signature, and remove"
check "install ${PK[*]}" pacman -S --noconfirm --needed $sd "${PK[@]}"
grep -E 'checking package integrity|signature|error' /tmp/c.out | sed 's/^/    | /' | head -6
for p in "${PK[@]}"; do
    check "$p installed, Validated By: Signature" bash -c "pacman -Qi $p | grep -E '^Validated By' | grep -q Signature"
done
check "pacman -Qk after install" bash -c 'pacman -Qk 2>/dev/null | grep -vc " 0 missing files" | grep -qx 0'
check "pacman -Dk after install" bash -c 'pacman -Dk 2>&1 | grep -q "No database errors have been found"'
check "remove ${PK[*]}" pacman -Rns --noconfirm "${PK[@]}"
for p in "${PK[@]}"; do check "$p is gone" bash -c "! pacman -Q $p"; done
check "pacman -Dk after removal" bash -c 'pacman -Dk 2>&1 | grep -q "No database errors have been found"'
check "pacman -Qk after removal" bash -c 'pacman -Qk 2>/dev/null | grep -vc " 0 missing files" | grep -qx 0'
check "reinstall ${PK[*]}" pacman -S --noconfirm --needed $sd "${PK[@]}"
check "second removal" pacman -Rns --noconfirm "${PK[@]}"

echo "== G-. what must be refused (the same real packages, tampered or untrusted)"
rm -rf /tmp/dl /tmp/neg; mkdir -p /tmp/dl /tmp/neg
check "download the probe package and its signature" pacman -Sw --noconfirm $sd --cachedir /tmp/dl perl-color-output
P=$(ls /tmp/dl/perl-color-output-*.pkg.tar.* | grep -v '\.sig$' | head -1); PB=$(basename "$P")
ls /tmp/dl | sed 's/^/    | /'
if [ -s "$P.sig" ]; then ok "the downloaded package has a detached signature"; else echo "INFO no .sig beside the cached package (pacman used the signature embedded in the database)"; fi
# a detached signature for the negative tests: from the repository when pacman fetched one, else from the mirror
if [ ! -s "$P.sig" ]; then curl -fsSL -o "$P.sig" "https://blackarch.org/blackarch/blackarch/os/aarch64/$PB.sig" && ok "fetched $PB.sig from the official origin"; fi
check "the untampered package + signature verify (control)" bash -c "$G --status-fd 1 --verify '$P.sig' '$P' 2>/dev/null | grep -q '^\[GNUPG:\] VALIDSIG F9A6E68A711354D84A9B91637533BAFE69A25079 '"

# n1: one flipped byte, the genuine signature
cp "$P" /tmp/neg/bad.pkg.tar.zst; cp "$P.sig" /tmp/neg/bad.pkg.tar.zst.sig
printf '\xff' | dd of=/tmp/neg/bad.pkg.tar.zst bs=1 seek=$(( $(stat -c %s "$P") / 2 )) conv=notrunc 2>/dev/null
refuse "pacman -U of a package altered after signing" 'invalid or corrupted|signature' pacman -U --noconfirm /tmp/neg/bad.pkg.tar.zst
check "...and nothing was installed" bash -c '! pacman -Q perl-color-output'

# n2: a signature from a key the keyring does not trust
mkdir -m 700 /tmp/neg/rogue; export GNUPGHOME_SAVE=${GNUPGHOME:-}
GNUPGHOME=/tmp/neg/rogue gpg --batch --passphrase '' --quick-generate-key 'Rogue <rogue@example.org>' ed25519 sign never >/dev/null 2>&1
cp "$P" /tmp/neg/rogue.pkg.tar.zst
GNUPGHOME=/tmp/neg/rogue gpg --batch --detach-sign -o /tmp/neg/rogue.pkg.tar.zst.sig /tmp/neg/rogue.pkg.tar.zst 2>/dev/null
refuse "pacman -U of a package signed by an untrusted key" 'unknown trust|unknown public key|signature|key' pacman -U --noconfirm /tmp/neg/rogue.pkg.tar.zst
check "...and nothing was installed" bash -c '! pacman -Q perl-color-output'

# a throwaway file:// repository named blackarch, under the shipped options and global SigLevel
mkrepo() { # mkrepo DIR : an empty file:// repository section
    mkdir -p "$1/repo" "$1/db/sync" "$1/cache"; cp -a /var/lib/pacman/local "$1/db/"
    sed '/^\[core\]/,$d' /etc/pacman.conf > "$1/pacman.conf"
    printf '[blackarch]\nServer = file://%s/repo\n' "$1" >> "$1/pacman.conf"
}
pm() { local d=$1; shift; pacman --config "$d/pacman.conf" --dbpath "$d/db" --cachedir "$d/cache" "$@"; }
chk_conf() { sh /builder/check-pacman-conf.sh /dev/null >/dev/null 2>&1; true; }
# n0: control: the genuine database, signature, package and signature
mkrepo /tmp/neg/n0; cp /var/lib/pacman/sync/blackarch.db /var/lib/pacman/sync/blackarch.db.sig /tmp/neg/n0/repo/; cp "$P" "$P.sig" /tmp/neg/n0/repo/
check "control: a file:// copy of the genuine repository installs perl-color-output" bash -c "pacman --config /tmp/neg/n0/pacman.conf --dbpath /tmp/neg/n0/db --cachedir /tmp/neg/n0/cache -Sy $sd --noconfirm >/dev/null 2>&1 && pacman --config /tmp/neg/n0/pacman.conf --dbpath /tmp/neg/n0/db --cachedir /tmp/neg/n0/cache -S $sd --noconfirm perl-color-output"
check "control: ...and it is there" bash -c 'pacman -Q perl-color-output >/dev/null 2>&1 || pacman --dbpath /tmp/neg/n0/db -Q perl-color-output'
# n3: unsigned database and unsigned package
mkrepo /tmp/neg/n3; cp "$P" /tmp/neg/n3/repo/; ( cd /tmp/neg/n3/repo && repo-add blackarch.db.tar.zst "$PB" >/dev/null 2>&1 )
pm /tmp/neg/n3 -Sy $sd --noconfirm >/dev/null 2>&1
refuse "installing an unsigned package from a repository" 'missing required signature|\.sig' pm /tmp/neg/n3 -S $sd --noconfirm perl-color-output
# n4: the genuine signature over a tampered database
mkrepo /tmp/neg/n4; cp /var/lib/pacman/sync/blackarch.db /var/lib/pacman/sync/blackarch.db.sig /tmp/neg/n4/repo/; printf 'x' >> /tmp/neg/n4/repo/blackarch.db; cp "$P" "$P.sig" /tmp/neg/n4/repo/
refuse "synchronising a tampered database" 'signature|invalid or corrupted database' pm /tmp/neg/n4 -Sy $sd --noconfirm
# n5: a genuine database and signature but a tampered package file in the repository
mkrepo /tmp/neg/n5; cp /var/lib/pacman/sync/blackarch.db /var/lib/pacman/sync/blackarch.db.sig /tmp/neg/n5/repo/; cp /tmp/neg/bad.pkg.tar.zst "/tmp/neg/n5/repo/$PB"; cp "$P.sig" "/tmp/neg/n5/repo/$PB.sig"
pm /tmp/neg/n5 -Sy $sd --noconfirm >/dev/null 2>&1
refuse "installing a repository package altered after signing" 'invalid or corrupted|signature|checksum' pm /tmp/neg/n5 -S $sd --noconfirm perl-color-output

echo "== the image's own configuration was not touched by any of it"
check "pacman.conf unchanged" bash -c 'test "$(sha256sum /etc/pacman.conf | cut -d" " -f1)" = "$(cat /tmp/conf.sha)"'
check "pacman.conf still passes the policy" sh /builder/check-pacman-conf.sh /etc/pacman.conf /builder/keyring.pins
echo "SUMMARY: $PASS PASS, $FAIL FAIL"
[ "$FAIL" -eq 0 ]
