imageId=ubuntu-26.04.1-base-arm64
ubuntuVersion=26.04.1
architecture=aarch64
sourceUrl=https://cdimage.ubuntu.com/ubuntu-base/releases/26.04/release/ubuntu-base-26.04.1-base-arm64.tar.gz
filename=ubuntu-base-26.04.1-base-arm64.tar.gz
assetName=ubuntu-base-26.04.1-base-arm64.tgz
upstreamSha256=5a1906794ced63a71a8119c3f211ef5f0bbe0a243001b4bbd41fdf80c5b219fd
compressedSize=35092106
uncompressedSize=122122240
schemaVersion=1
prootSource=https://github.com/Lord1Egypt/ProotX-Assets-Support/releases/download/v1.2.0/arm64-v8a-assets.zip
prootVersion=ProotX-v1.2.0-modern
prootSha256=42fd0042b18d8145ebb72aece000404bed8a0911c83505c1acf31e2da5033fe7
