imageId=ubuntu-26.04.1-base-arm64
ubuntuVersion=26.04.1
architecture=aarch64
sourceUrl=https://cdimage.ubuntu.com/ubuntu-base/releases/26.04/release/ubuntu-base-26.04.1-base-arm64.tar.gz
filename=ubuntu-base-26.04.1-base-arm64.tar.gz
assetName=ubuntu-base-26.04.1-base-arm64.tgz
upstreamSha256=5a1906794ced63a71a8119c3f211ef5f0bbe0a243001b4bbd41fdf80c5b219fd
compressedSize=35092106
uncompressedSize=122122240
schemaVersion=1
